ChannelWorm/channelworm/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^digitizer/', include('digitizer.urls', namespace="digitizer"), ),
    url(r'^ion_channel/', include('ion_channel.urls', namespace="ion_channel"), ),
    url(r'^index$', 'ion_channel.views.index' ),
    url(r'^$', 'ion_channel.views.index' ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChannelWorm/digitizer/urls.py
from django.conf.urls import url

from digitizer import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^cvs_export/$', views.csv_export, name='csv_export'),
    url(r'^(?P<graph_id>[0-9]+)$', views.digitize, name='digitize'),
]

ChannelWorm/ion_channel/urls.py
from django.conf.urls import include, url

from ion_channel import views
from ion_channel.views import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^experiment/create/$', ExperimentCreate.as_view(), name='experiment-create'),
    url(r'^home$', ExperimentList.as_view(), name='home'),
    url(r'^experiment$', ExperimentList.as_view(), name='experiment-index'),
    url(r'^experiment/update/(?P<pk>[0-9]+)$', ExperimentUpdate.as_view(), name='experiment-update'),
    url(r'^experiment/delete/(?P<pk>[0-9]+)$', ExperimentDelete.as_view(), name='experiment-delete'),

    url(r'^channel_model$', IonChannelList.as_view(), name='ion-channel-index'),
    url(r'^channel_model/create$', IonChannelCreate.as_view(), name='ion-channel-create'),
    url(r'^channel_model/update/(?P<pk>[0-9]+)$', IonChannelUpdate.as_view(), name='ion-channel-update'),
    url(r'^channel_model/delete/(?P<pk>[0-9]+)$', IonChannelDelete.as_view(), name='ion-channel-delete'),

    url(r'^patch_clamp$', PatchClampList.as_view(), name='patch-clamp-index'),
    url(r'^patch_clamp/create$', PatchClampCreate.as_view(), name='patch-clamp-create'),
    url(r'^patch_clamp/update/(?P<pk>[0-9]+)$', PatchClampUpdate.as_view(), name='patch-clamp-update'),
    url(r'^patch_clamp/delete/(?P<pk>[0-9]+)$', PatchClampDelete.as_view(), name='patch-clamp-delete'),

    url(r'^graph$', GraphList.as_view(), name='graph-index'),
    url(r'^graph/create$', GraphCreate.as_view(), name='graph-create'),
    url(r'^graph/update/(?P<pk>[0-9]+)$', GraphUpdate.as_view(), name='graph-update'),
    url(r'^graph/delete/(?P<pk>[0-9]+)$', GraphDelete.as_view(), name='graph-delete'),

    url(r'^graph_data/(?P<graph_id>[0-9]+)$', GraphDataList.as_view(), name='graph-data-index'),
    url(r'^graph_data/create$', save_graph_data, name='graph-data-create'),
    url(r'^graph_data/delete/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', GraphDataDelete.as_view(), name='graph-data-delete'),

]

ChannelWorm/ion_channel/models.py
from django.db import models

# Create your models here.

class Experiment(models.Model):
    doi = models.CharField(max_length=300)

    def __unicode__(self):
        return self.doi


class IonChannelModel(models.Model):
    experiment = models.ForeignKey(Experiment)
    channel_type = models.CharField(max_length=300)
    ion_type = models.CharField(max_length=300)
    expressions = models.CharField(max_length=300)

    def __unicode__(self):
        return self.channel_type + self.ion_type


class PatchClamp(models.Model):
    experiment = models.ForeignKey(Experiment)
    type = models.CharField(max_length=200)
    duration = models.IntegerField()
    delta = models.IntegerField()
    start_time = models.IntegerField()
    end_time = models.IntegerField()
    protocol_start = models.IntegerField()
    protocol_end = models.IntegerField()
    protocol_step = models.IntegerField()

    def __unicode__(self):
        return self.type + " " + `self.duration`


class Graph(models.Model):
    experiment = models.ForeignKey(Experiment, null=True, blank=True)
    patch_clamp = models.ForeignKey(PatchClamp, null=True, blank=True)

    x_axis_type = models.CharField(max_length=50)
    x_axis_unit = models.CharField(max_length=50)

    y_axis_type = models.CharField(max_length=50)
    y_axis_unit = models.CharField(max_length=50)

    figure_ref_address = models.CharField(max_length=500)
    figure_ref_caption = models.CharField(max_length=100)
    file = models.ImageField(upload_to='ion_channel/graph/%Y/%m/%d')

    def __unicode__(self):
        return self.x_axis_type + " " + self.x_axis_unit


class GraphData(models.Model):
    graph = models.ForeignKey(Graph)
    series_name = models.CharField(max_length=200)
    series_data = models.TextField()

ChannelWorm/ion_channel/views.py
import json
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from ion_channel.models import Experiment, IonChannelModel, PatchClamp, Graph, GraphData


def index(request):
    return render(request, 'ion_channel/index.html')


class ExperimentList(ListView):
    model = Experiment
    context_object_name = 'experiments'


class ExperimentCreate(CreateView):
    model = Experiment
    fields = ['doi']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('ion_channel:experiment-index')


class ExperimentUpdate(UpdateView):
    model = Experiment
    fields = ['doi']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('ion_channel:experiment-index')


class ExperimentDelete(DeleteView):
    model = Experiment
    success_url = reverse_lazy('ion_channel:experiment-index')


class IonChannelList(ListView):
    model = IonChannelModel
    context_object_name = 'ion_channel_models'


class IonChannelCreate(CreateView):
    model = IonChannelModel
    fields = '__all__'
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('ion_channel:ion-channel-index')


class IonChannelUpdate(UpdateView):
    model = IonChannelModel
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('ion_channel:ion-channel-index')


class IonChannelDelete(DeleteView):
    model = IonChannelModel
    success_url = reverse_lazy('ion_channel:ion-channel-index')


class PatchClampList(ListView):
    model = PatchClamp
    context_object_name = 'patch_clamps'


class PatchClampCreate(CreateView):
    model = PatchClamp
    fields = '__all__'
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('ion_channel:patch-clamp-index')


class PatchClampUpdate(UpdateView):
    model = PatchClamp
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('ion_channel:patch-clamp-index')


class PatchClampDelete(DeleteView):
    model = PatchClamp
    success_url = reverse_lazy('ion_channel:patch-clamp-index')


class GraphList(ListView):
    model = Graph
    context_object_name = 'graphs'


class GraphCreate(CreateView):
    model = Graph
    fields = '__all__'
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('ion_channel:graph-index')


class GraphUpdate(UpdateView):
    model = Graph
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('ion_channel:graph-index')


class GraphDelete(DeleteView):
    model = Graph
    success_url = reverse_lazy('ion_channel:graph-index')


class GraphDataList(ListView):
    model = GraphData
    context_object_name = 'graph_data'

    def get_queryset(self):
        print self.kwargs
        self.graph = get_object_or_404(Graph, id=self.kwargs['graph_id'])
        return GraphData.objects.filter(graph=self.graph)


class GraphDataDelete(DeleteView):
    model = GraphData

    def get_success_url(self):
        return reverse_lazy('ion_channel:graph-data-index', kwargs={'graph_id': self.object.graph_id})


def save_graph_data(request):
    response_data = {'status': 'error', 'result': 'Saving graph data has been failed'}
    print response_data
    if request.method == 'POST':
        print "is post"
        graph = get_object_or_404(Graph, pk=request.POST.get("graph_id"))
        data = GraphData(graph=graph, series_name=request.POST.get("series_name"),
                         series_data=request.POST.get("series_data"))
        data.save()
        response_data = {'status': 'success', 'result': 'Graph data has been saved.'}

    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )

ChannelWorm/ion_channel/templates/ion_channel/experiment_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Delete Experiment' %}{% endblock %}
{% block page_header %}{% trans 'Delete Experiment' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li><a href="{% url 'ion_channel:experiment-index' %}">{% trans 'Experiments' %}</a></li>
    <li class="active">{% trans 'Delete' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-warning">
                <div class="box-header">
                    <i class="fa fa-warning"></i>

                    <h3 class="box-title">{% trans 'Confirmation' %}</h3>
                </div>
                <form method="post" class="form">
                    {% csrf_token %}
                    <div class="box-body">
                        <div class="callout callout-warning">
                            <p>
                                {% blocktrans %}
                                    Are you sure you want to delete the <strong>"{{ object }}"<strong>?
                                {% endblocktrans %}
                            </p>
                        </div>
                    </div>
                    <div class="box-footer">
                        <input type="submit" value="{% trans 'Yes' %}" class="btn btn-success"/>
                        <a href="{% url 'ion_channel:experiment-index' %}" class="btn btn-default">{% trans 'No' %}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/experiment_list.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Experiment List' %}{% endblock %}
{% block page_header %}{% trans 'Experiment List' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Experiments' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-flask"></i>

                    <h3 class="box-title">{% trans 'Experiment' %}</h3>

                    <div class="box-tools pull-right">
                        <a href="{% url 'ion_channel:experiment-create' %}"
                           class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i>
                            {% trans 'Add Experiment' %}
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <table id="experiments_table" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>{% trans 'DOI' %}</th>
                            <th style="width: 200px">{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for experiment in experiments %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{ experiment.doi }}</td>
                                <td>
                                    <a href="{% url 'ion_channel:experiment-update' experiment.id %}"
                                       class="badge bg-light-blue">
                                        <i class="fa fa-edit"></i>
                                        {% trans 'Edit' %}
                                    </a>
                                    <a href="{% url 'ion_channel:experiment-delete' experiment.id %}"
                                       class="badge bg-red">
                                        <i class="fa fa-remove"></i>
                                        {% trans 'Delete' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block inline-script %}
    <script type="text/javascript">
        $("#experiments_table").dataTable();
    </script>
{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/experiment_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Update Experiment' %}{% endblock %}
{% block page_header %}{% trans 'Update Experiment' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li><a href="{% url 'ion_channel:experiment-index' %}">{% trans 'Experiments' %}</a></li>
    <li class="active">{% trans 'Update' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">{% trans 'Experiment' %}</h3>
                </div>
                <form method="post" class="form">
                    <div class="box-body">
                        {% csrf_token %}
                        {% for field in form%}
                            <div class="form-group">
                                {{ field.errors }}
                                {{ field.label_tag }}
                                {{ field |addcss:"form-control" }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="box-footer">
                        <input type="submit" value="Submit" class="btn btn-primary"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/graph_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Delete Graph' %}{% endblock %}
{% block page_header %}{% trans 'Delete Graph' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li><a href="{% url 'ion_channel:graph-index' %}">{% trans 'Graphs' %}</a></li>
    <li class="active">{% trans 'Delete' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-warning">
                <div class="box-header">
                    <i class="fa fa-warning"></i>

                    <h3 class="box-title">{% trans 'Confirmation' %}</h3>
                </div>
                <form method="post" class="form">
                    {% csrf_token %}
                    <div class="box-body">
                        <div class="callout callout-warning">
                            <p>
                                {% blocktrans %}
                                    Are you sure you want to delete the Graph?
                                {% endblocktrans %}
                            </p>
                        </div>
                    </div>
                    <div class="box-footer">
                        <input type="submit" value="{% trans 'Yes' %}" class="btn btn-success"/>
                        <a href="{% url 'ion_channel:graph-index' %}" class="btn btn-default">{% trans 'No' %}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/graph_list.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Graph List' %}{% endblock %}
{% block page_header %}{% trans 'Graph List' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Graphs' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-bar-chart"></i>

                    <h3 class="box-title">{% trans 'Graph' %}</h3>

                    <div class="box-tools pull-right">
                        <a href="{% url 'ion_channel:graph-create' %}"
                           class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i>
                            {% trans 'Add Graph' %}
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <table id="result_table" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>{% trans 'X Type' %}</th>
                            <th>{% trans 'X Unit' %}</th>
                            <th>{% trans 'Y Type' %}</th>
                            <th>{% trans 'Y Unit' %}</th>
                            <th>{% trans 'Ref Address' %}</th>
                            <th>{% trans 'Ref Cpation' %}</th>
                            <th>{% trans 'Patch Clamp' %}</th>
                            <th>{% trans 'Experiment' %}</th>
                            <th>{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for graph in graphs %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ graph.x_axis_type }}</td>
                                <td>{{ graph.x_axis_unit }}</td>
                                <td>{{ graph.y_axis_type }}</td>
                                <td>{{ graph.y_axis_unit }}</td>
                                <td>{{ graph.figure_ref_address }}</td>
                                <td>{{ graph.figure_ref_caption }}</td>
                                <td>{{ graph.patch_clamp }}</td>
                                <td>{{ graph.experiment }}</td>
                                <td>
                                    <a href="{% url 'ion_channel:graph-update' graph.id %}"
                                       class="badge bg-light-blue">
                                        <i class="fa fa-edit"></i>
                                        {% trans 'Edit' %}
                                    </a>
                                    <a href="{% url 'ion_channel:graph-delete' graph.id %}"
                                       class="badge bg-red">
                                        <i class="fa fa-remove"></i>
                                        {% trans 'Delete' %}
                                    </a>
                                    <a href="{% url 'digitizer:digitize' graph.id %}"
                                       class="badge bg-green">
                                        <i class="fa fa-file-text-o"></i>
                                        {% trans 'Digitize' %}
                                    </a>
                                    <a href="{% url 'ion_channel:graph-data-index' graph.id %}"
                                       class="badge bg-yellow">
                                        <i class="fa fa-file-text-o"></i>
                                        {% trans 'Series' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block inline-script %}
    <script type="text/javascript">
        $("#result_table").dataTable();
    </script>
{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/graphdata_list.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Graph Data List' %}{% endblock %}
{% block page_header %}{% trans 'Graph Data List' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li><a href="{% url 'ion_channel:graph-index' %}"><i class="fa fa-bar-chart"></i> {% trans 'Graph' %}</a></li>
    <li class="active">{% trans 'Graph Data' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-file-text-o"></i>

                    <h3 class="box-title">{% trans 'Graph Data' %}</h3>
                </div>
                <div class="box-body">
                    <table id="result_table" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>{% trans 'Series Name' %}</th>
                            <th>{% trans 'Series Data' %}</th>
                            <th>{% trans 'Graph' %}</th>
                            <th>{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for data in graph_data %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ data.series_name }}</td>
                                <td>{{ data.series_data }}</td>
                                <td>{{ data.graph }}</td>
                                <td>
                                    <a href="{% url 'ion_channel:graph-data-delete' data.graph.id data.id %}"
                                       class="badge bg-red">
                                        <i class="fa fa-remove"></i>
                                        {% trans 'Delete' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block inline-script %}
    <script type="text/javascript">
        $("#result_table").dataTable();
    </script>
{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/index.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}{% trans 'Home' %}{% endblock %}
{% block page_header %}{% trans 'Home' %}{% endblock %}
{% block breadcrumb %}

{% endblock %}

{% block content %}

{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/ionchannelmodel_list.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Ion Channel Model List' %}{% endblock %}
{% block page_header %}{% trans 'Ion Channel Model List' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Ion Channel Models' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-neuter"></i>

                    <h3 class="box-title">{% trans 'Ion Channel Model' %}</h3>

                    <div class="box-tools pull-right">
                        <a href="{% url 'ion_channel:ion-channel-create' %}"
                           class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i>
                            {% trans 'Add Ion Channel Model' %}
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <table id="result_table" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>{% trans 'Channel Type' %}</th>
                            <th>{% trans 'Ion Type' %}</th>
                            <th>{% trans 'Expressions' %}</th>
                            <th>{% trans 'Experiment' %}</th>
                            <th style="width: 200px">{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ion_channel in ion_channel_models %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{ ion_channel.channel_type }}</td>
                                <td>{{ ion_channel.ion_type }}</td>
                                <td>{{ ion_channel.expressions }}</td>
                                <td>{{ ion_channel.experiment.doi }}</td>
                                <td>
                                    <a href="{% url 'ion_channel:ion-channel-update' ion_channel.id %}"
                                       class="badge bg-light-blue">
                                        <i class="fa fa-edit"></i>
                                        {% trans 'Edit' %}
                                    </a>
                                    <a href="{% url 'ion_channel:ion-channel-delete' ion_channel.id %}"
                                       class="badge bg-red">
                                        <i class="fa fa-remove"></i>
                                        {% trans 'Delete' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block inline-script %}
    <script type="text/javascript">
        $("#result_table").dataTable();
    </script>
{% endblock %}

ChannelWorm/ion_channel/templates/ion_channel/patchclamp_list.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Patch Clamp List' %}{% endblock %}
{% block page_header %}{% trans 'Patch Clamp List' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Patch Clamps' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-pinterest-p"></i>

                    <h3 class="box-title">{% trans 'Patch Clamp' %}</h3>

                    <div class="box-tools pull-right">
                        <a href="{% url 'ion_channel:patch-clamp-create' %}"
                           class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i>
                            {% trans 'Add Patch Clamp' %}
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <table id="result_table" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>{% trans 'Type' %}</th>
                            <th>{% trans 'Duration' %}</th>
                            <th>{% trans 'Delta' %}</th>
                            <th>{% trans 'Start Time' %}</th>
                            <th>{% trans 'End Time' %}</th>
                            <th>{% trans 'Protocol Start' %}</th>
                            <th>{% trans 'Protocol End' %}</th>
                            <th>{% trans 'Protocol Step' %}</th>
                            <th>{% trans 'Experiment' %}</th>
                            <th>{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for patch_clamp in patch_clamps %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{ patch_clamp.type }}</td>
                                <td>{{ patch_clamp.duration }}</td>
                                <td>{{ patch_clamp.delta }}</td>
                                <td>{{ patch_clamp.start_time }}</td>
                                <td>{{ patch_clamp.end_time }}</td>
                                <td>{{ patch_clamp.protocol_start }}</td>
                                <td>{{ patch_clamp.protocol_end }}</td>
                                <td>{{ patch_clamp.protocol_step }}</td>
                                <td>{{ patch_clamp.experiment.doi }}</td>
                                <td>
                                    <a href="{% url 'ion_channel:patch-clamp-update' patch_clamp.id %}"
                                       class="badge bg-light-blue">
                                        <i class="fa fa-edit"></i>
                                        {% trans 'Edit' %}
                                    </a>
                                    <a href="{% url 'ion_channel:patch-clamp-delete' patch_clamp.id %}"
                                       class="badge bg-red">
                                        <i class="fa fa-remove"></i>
                                        {% trans 'Delete' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block inline-script %}
    <script type="text/javascript">
        $("#result_table").dataTable();
    </script>
{% endblock %}