ChannelWorm/channelworm/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^digitizer/', include('digitizer.urls', namespace="digitizer"), ),
    url(r'^ion_channel/', include('ion_channel.urls', namespace="ion_channel"), ),
    url(r'^index$', 'ion_channel.views.index' ),
    url(r'^$', 'ion_channel.views.index' ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChannelWorm/digitizer/urls.py
from django.conf.urls import url

from digitizer import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^cvs_export/$', views.csv_export, name='csv_export'),
    url(r'^(?P<graph_id>[0-9]+)$', views.digitize, name='digitize'),
]

ChannelWorm/ion_channel/urls.py
from django.conf.urls import include, url

from ion_channel import views
from ion_channel.views import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^experiment/create/$', ExperimentCreate.as_view(), name='experiment-create'),
    url(r'^home$', ExperimentList.as_view(), name='home'),
    url(r'^experiment$', ExperimentList.as_view(), name='experiment-index'),
    url(r'^experiment/update/(?P<pk>[0-9]+)$', ExperimentUpdate.as_view(), name='experiment-update'),
    url(r'^experiment/delete/(?P<pk>[0-9]+)$', ExperimentDelete.as_view(), name='experiment-delete'),

    url(r'^channel_model$', IonChannelList.as_view(), name='ion-channel-index'),
    url(r'^channel_model/create$', IonChannelCreate.as_view(), name='ion-channel-create'),
    url(r'^channel_model/update/(?P<pk>[0-9]+)$', IonChannelUpdate.as_view(), name='ion-channel-update'),
    url(r'^channel_model/delete/(?P<pk>[0-9]+)$', IonChannelDelete.as_view(), name='ion-channel-delete'),

    url(r'^patch_clamp$', PatchClampList.as_view(), name='patch-clamp-index'),
    url(r'^patch_clamp/create$', PatchClampCreate.as_view(), name='patch-clamp-create'),
    url(r'^patch_clamp/update/(?P<pk>[0-9]+)$', PatchClampUpdate.as_view(), name='patch-clamp-update'),
    url(r'^patch_clamp/delete/(?P<pk>[0-9]+)$', PatchClampDelete.as_view(), name='patch-clamp-delete'),

    url(r'^graph$', GraphList.as_view(), name='graph-index'),
    url(r'^graph/create$', GraphCreate.as_view(), name='graph-create'),
    url(r'^graph/update/(?P<pk>[0-9]+)$', GraphUpdate.as_view(), name='graph-update'),
    url(r'^graph/delete/(?P<pk>[0-9]+)$', GraphDelete.as_view(), name='graph-delete'),

    url(r'^graph_data/(?P<graph_id>[0-9]+)$', GraphDataList.as_view(), name='graph-data-index'),
    url(r'^graph_data/create$', save_graph_data, name='graph-data-create'),
    url(r'^graph_data/delete/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', GraphDataDelete.as_view(), name='graph-data-delete'),

]

ChannelWorm/digitizer/models.py
from django.db import models

ChannelWorm/digitizer/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404


# Create your views here.
from ion_channel.models import Graph


def index(request):
    return render(request, 'digitizer/index.html')


def digitize(request, graph_id):
    graph = get_object_or_404(Graph, pk=graph_id)
    return render(request, 'digitizer/index.html', {'graph': graph})


def csv_export(request):
    data = request.POST.get("data")
    file_name = request.POST.get("filename")
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="' + file_name + '.csv"'

    response.write(json.loads(data))
    return response

ChannelWorm/digitizer/templates/digitizer/index.html
{% extends "base_collapsed_sidebar.html" %}

{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans 'WebPlotDigitizer - Copyright 2010-2015 Ankit Rohatgi' %}{% endblock %}
{% block page_header %}{% trans 'Digitizer' %}{% endblock %}
{% block page_header_description %}{% trans 'Digitizing graphs' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li><a href="{% url 'ion_channel:graph-index' %}"><i class="fa fa-bar-chart"></i> {% trans 'Graph' %}</a></li>
    <li class="active">{% trans 'Digitizer' %}</li>
{% endblock %}

{% block inline-css %}
    <link rel="stylesheet" href="{% static 'digitizer/thirdparty/toastr/toastr.min.css' %}" type="text/css"
          media="screen"/>
    <link rel="stylesheet" href="{% static 'digitizer/css/cwd-style.css' %}" type="text/css" media="screen"/>
{% endblock %}

{% block inline-script %}
    {% include 'digitizer/includes/_scripts.html' %}
    <script src="{% static 'digitizer/js/cwd.js' %}"></script>
    <script src="{% static 'digitizer/thirdparty/numeric-1.2.6.min.js' %}"></script>
    <script src="{% static 'digitizer/thirdparty/toastr/toastr.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="loadingCurtain" style="display:none">Loading application, please wait...</div>
    <form id="frm_graph_data" method="post" class="form" action="{% url 'ion_channel:graph-data-create' %}">
        {% csrf_token %}
        <input type="hidden" id="graph_url" name="graph_url" value="/media/{{ graph.file }}"/>
        <input type="hidden" id="graph_id" name="graph_id" value="{{ graph.id }}"/>
        <input type="hidden" id="series_name" name="series_name"/>
        <input type="hidden" id="series_data" name="series_data"/>
    </form>

    <div class="row" id="allContainer">
        {% include 'digitizer/includes/_toolbox.html' %}
        <div id="mainContainer" class="col-sm-9">
            <div id="graphicsContainer" class="box box-primary">

                {% include 'digitizer/includes/_toolbars.html' %}
                <div class="box-body">
                    <div id="canvasDiv" style="position:relative;" class="box-body">
                        <canvas id="mainCanvas" class="canvasLayers" style="z-index:1;" width=600 height=400></canvas>
                        <canvas id="dataCanvas" class="canvasLayers" style="z-index:2;" width=600 height=400></canvas>
                        <canvas id="drawCanvas" class="canvasLayers" style="z-index:3;" width=600 height=400></canvas>
                        <canvas id="hoverCanvas" class="canvasLayers" style="z-index:4;" width=600 height=400></canvas>
                        <canvas id="topCanvas" class="canvasLayers" style="z-index:5;" width=600 height=400></canvas>
                    </div>
                </div>
                <div class="overlay cwd-loading">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
    <!-- popup windows go here -->
    {% include 'digitizer/includes/_dialogs.html' %}
{% endblock %}