ChannelWorm/channelworm/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^digitizer/', include('digitizer.urls', namespace="digitizer"), ),
    url(r'^ion_channel/', include('ion_channel.urls', namespace="ion_channel"), ),
    url(r'^index$', 'ion_channel.views.index' ),
    url(r'^$', 'ion_channel.views.index' ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChannelWorm/digitizer/urls.py
from django.conf.urls import url

from digitizer import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^cvs_export/$', views.csv_export, name='csv_export'),
    url(r'^(?P<graph_id>[0-9]+)$', views.digitize, name='digitize'),
]

ChannelWorm/ion_channel/urls.py
from django.conf.urls import include, url

from ion_channel import views
from ion_channel.views import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^experiment/create/$', ExperimentCreate.as_view(), name='experiment-create'),
    url(r'^home$', ExperimentList.as_view(), name='home'),
    url(r'^experiment$', ExperimentList.as_view(), name='experiment-index'),
    url(r'^experiment/update/(?P<pk>[0-9]+)$', ExperimentUpdate.as_view(), name='experiment-update'),
    url(r'^experiment/delete/(?P<pk>[0-9]+)$', ExperimentDelete.as_view(), name='experiment-delete'),

    url(r'^channel_model$', IonChannelList.as_view(), name='ion-channel-index'),
    url(r'^channel_model/create$', IonChannelCreate.as_view(), name='ion-channel-create'),
    url(r'^channel_model/update/(?P<pk>[0-9]+)$', IonChannelUpdate.as_view(), name='ion-channel-update'),
    url(r'^channel_model/delete/(?P<pk>[0-9]+)$', IonChannelDelete.as_view(), name='ion-channel-delete'),

    url(r'^patch_clamp$', PatchClampList.as_view(), name='patch-clamp-index'),
    url(r'^patch_clamp/create$', PatchClampCreate.as_view(), name='patch-clamp-create'),
    url(r'^patch_clamp/update/(?P<pk>[0-9]+)$', PatchClampUpdate.as_view(), name='patch-clamp-update'),
    url(r'^patch_clamp/delete/(?P<pk>[0-9]+)$', PatchClampDelete.as_view(), name='patch-clamp-delete'),

    url(r'^graph$', GraphList.as_view(), name='graph-index'),
    url(r'^graph/create$', GraphCreate.as_view(), name='graph-create'),
    url(r'^graph/update/(?P<pk>[0-9]+)$', GraphUpdate.as_view(), name='graph-update'),
    url(r'^graph/delete/(?P<pk>[0-9]+)$', GraphDelete.as_view(), name='graph-delete'),

    url(r'^graph_data/(?P<graph_id>[0-9]+)$', GraphDataList.as_view(), name='graph-data-index'),
    url(r'^graph_data/create$', save_graph_data, name='graph-data-create'),
    url(r'^graph_data/delete/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', GraphDataDelete.as_view(), name='graph-data-delete'),

]

ChannelWorm/channelworm/templates/include/_main_header.html
{% load staticfiles %}
<header class="main-header">
    <!-- Logo -->
    <a href="/index" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><strong>CW</strong></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><strong>ChannelWorm</strong></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{% static 'third_party/lte/dist/img/avatar5.png' %}" class="user-image"
                             alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">Sample User</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{% static 'third_party/lte/dist/img/avatar5.png' %}" class="img-circle"
                                 alt="User Image"/>

                            <p>
                                Sample User - Job
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>-->
            </ul>
        </div>
    </nav>
</header>

ChannelWorm/channelworm/templates/include/_main_sidebar.html
{% load staticfiles %}
{% load i18n %}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% static 'third_party/lte/dist/img/avatar5.png' %}" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p>Sample User</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <!-- Optionally, you can add icons to the links -->
            <li><a href="{% url 'ion_channel:experiment-index' %}">
                <i class='fa fa fa-flask'></i><span>{% trans 'Experiments' %}</span></a>
            </li>
            <li><a href="{% url 'ion_channel:ion-channel-index' %}">
                <i class='fa fa-neuter'></i><span>{% trans 'Ion Channel Model' %}</span></a>
            </li>
            <li><a href="{% url 'ion_channel:patch-clamp-index' %}">
                <i class='fa fa-pinterest-p'></i><span>{% trans 'Patch Clamp' %}</span></a>
            </li>
            <li><a href="{% url 'ion_channel:graph-index' %}">
                <i class='fa fa-bar-chart'></i><span>{% trans 'Graph' %}</span></a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>